services:
  - type: web
    name: meetbot-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: VEXA_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
